import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import { Lato } from "next/font/google";
import "./globals.css";
import { clsx } from "clsx";

const lato = Lato({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Analytics />
      <body className="bg-neutral-50">
        <main
          className={clsx(
            "container shadow-lg print:shadow-none relative mx-auto scroll-my-12 bg-white overflow-auto mt-0 max-w-screen-md sm:p-12 p-[10vw]"
          )}
        >
          {children}
        </main>
      </body>
    </html>
  );
}
